# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MetropolLifeiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'MessageKit'
  pod 'InputBarAccessoryView'
  pod 'SnapKit'
  pod 'Starscream'
  pod 'AdvancedPageControl'
  pod 'Alamofire'
  # Pods for MetropolLifeiOS

end
